octokit/plugin-paginate-rest.js

- src/normalize-paginated-list-response.ts
- test/paginate.test.ts
> paginate map function can read `response.data[namespaceKey]` for name spaced endpoints

- src/normalize-paginated-list-response.ts
- test/paginate.test.ts
`GET /repos/:owner/:repo/actions/runs/:run_id/artifacts`, key: `artifacts`
`GET /repos/:owner/:repo/actions/secrets`, key: `secrets`
`GET /repos/:owner/:repo/actions/workflows`, key: `workflows`
`GET /repos/:owner/:repo/actions/runs/:run_id/jobs`, key: `jobs`
`GET /repos/:owner/:repo/actions/workflows/:workflow_id/runs`, key: `workflow_runs`
`GET /repos/:owner/:repo/actions/runs`, key: `workflow_runs`
> Workarounds for new actions endpoints

- package.json
this still works with @octokit/core version 2. The peerDependencies value of `>=3` is causing a peer dependency warning when downloading the `@octokit/rest` version 17 dependency tree.
@gr2m
> fix(package): lower peerDependency on `@octokit/core` to `>=2`

- src/index.ts
https://github.com/octokit/plugin-paginate-rest.js/pull/130#issuecomment-689077360
> fix(typescript): replaced `import type` with `import` to support TypeScript <3.8

- src/index.ts
- src/types.ts
- test/validate-typescript.ts
``PaginatingEndpoints`` appears in definition of arguments to ``composePaginateRest``. For most of its overloads (defined in ``ComposePaginateInterface``) the user is able to obtain information about argument types. Sometimes it's just a matter of importing an appropriate type from ``@octokit/types``, in some other cases a relativelly simple type, such as``MapFunction`` has to be redefined in user's code. The ``PaginatingEndpoints`` is an exception, because it's far from being "relativelly simple" . I think it's reasonable to expose this type to users.
> feat(typescript): expose PaginatingEndpoints to user

- src/types.ts
Redefines the ``MapFunction`` generic interface, such that it can be reused in a definition of all the overloads in ``PaginateInerface``/``ComposePaginateInterface``. This shall also prevent further bugs such as #259.
> fix(typescript): improve internal MapFunction type

- src/types.ts
Minor fix. Removes some inconsistencies within PaginateInterface/ComposePaginateInterface.
> fix(typescript): inconsistencies in parameter names

- package-lock.json
- src/types.ts
A cosmetic change - use consistently ``M`` as ``MapFunction``'s second parameter's name.
> MapFunction<*,{R|MR}> => MapFunction<*,M>

- scripts/update-endpoints/fetch-json.js
- scripts/update-endpoints/typescript.js
- src/generated/paginating-endpoints.ts
This PR adds pagination support for 2 APIs launched recently by GitHub:
* `GET /orgs/{org}/actions/cache/usage-by-repository`
* `GET  /repos/{owner}/{repo}/actions/caches`
It also adds pagination support for 10 APIs that have existed for a while, but were not supported in this plugin due to issues with our logic for detecting endpoints with pagination support:
* `GET /licenses`
* `GET /enterprises/{enterprise}/audit-log`
* `GET /orgs/{org}/audit-log`
* `GET /orgs/{org}/settings/billing/advanced-security`
* `GET /enterprises/{enterprise}/settings/billing/advanced-security`
* `GET /organizations/:organization_id/packages/:package_type/:package/versions`
* `GET /repos/{owner}/{repo}/commits/{ref}/status`
* `GET /repos/{owner}/{repo}/environments`
* `GET /repos/{owner}/{repo}/topics`
* `GET …
> feat: add pagination support for 2 new APIs and 10 existing ones which were missed

- src/types.ts
Followup to https://github.com/octokit/endpoint.js/pull/382#issuecomment-1370197900
See also https://github.com/octokit/endpoint.js/pull/388
Requires https://github.com/octokit/types.ts/pull/491
----
* Previews were documented
* Previews are no longer documented
* 
----
If `Yes`, what's the impact:  
* Removal of previews
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`
----
> docs: remove previews

- package-lock.json
- package.json
Resolves #ISSUE_NUMBER
----
* `@octokit/tsconfig` would always get pulled in
* `@octokit/tsconfig` is no longer pulled in, it is now marked as a dev dependency
*
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
Please add the corresponding label for change this PR introduces:
- Dependencies/code cleanup: `Type: Maintenance`
----
> chore(deps): move `@octokit/tsconfig` to a devDependency

- src/iterator.ts
Just looked through the code and found this line, I remembered why we put it in and figured we should add a comment for future me that will forget it for sure 👴🏼
> docs: add comment explaining handling of `409 conflict` error

- package.json
- scripts/build.mjs
- src/compose-paginate.ts
- src/index.ts
- src/iterator.ts
- src/normalize-paginated-list-response.ts
- src/paginate.ts
- src/paginating-endpoints.ts
- src/types.ts
- test/compose-paginate.test.ts
- test/issues.test.ts
- test/paginate.test.ts
- test/paginating-endpoints.test.ts
- test/smoke.test.ts
- test/tsconfig.test.json
- test/validate-typescript.ts
This PR replaces NodeJS internal module imports with `node:` specifier imports.
> refactor: use`node:` specifier imports and full relative path imports

- package.json
Resolves https://github.com/octokit/plugin-paginate-rest.js/issues/597
----
*  Octokit/core@6 is now ESM, which while this version is still CJS can't pull in and use.
*  Pinning this back to Octokit/core@5 where it remains CJS fixes this.
----
> fix(pkg): pin `@octokit/core` peerDependency to v5

- package-lock.json
- package.json
- scripts/build.mjs
- scripts/update-endpoints/fetch-json.js
- scripts/update-endpoints/typescript.js
- src/paginate.ts
- test/paginate.test.ts
BREAKING CHANGE: package is now ESM
> feat: package is now ESM

- README.md
- scripts/build.mjs
Resolves octokit/core.js#667 
Resolves octokit/core.js#665
---
- Some consumers of this package could not resolve it properly (ex: `jest`, `ts-node`, `tsx`)
- CJS consumers would be getting errors even though the package is ESM
- Consumers cannot import paths from the package like in CJS
- Clients should be able to import the module without any errors with the fallback
- CJS consumers will generate a better error with the new fallback
- Consumers are able to import types from the `dist-types/types.d.ts` file in the package
---
> fix(pkg): add default fallback and types export

- README.md
Resolves #ISSUE_NUMBER
----
* The readme uses CJS syntax
* The README uses ESM syntax
----
> docs(README): update examples to use ESM

- package.json
- src/iterator.ts
- src/paginate.ts
- src/types.ts
The `iterator()` function returns an object containing a key of `Symbol.asyncIterator`, which is an object with a `next()` function. Only the top-level has the `Symbol.asyncIterator`, and the `next()` function is not present at the top-level
The `GetResultsType<T>` sometimes doesn't return the paginated data and returns the whole data object. For some reason TypeScript sometimes get's confused and returns all the keys in the object in the call `KnownKeysMatching<T["data"], any[]>`
In order to remedy that, we remove keys that we know do not contain the data (`"repository_selection" | "total_count" | "incomplete_results"`) and we then always get the data.
The `NormalizeResponse<T>` type would return the intersection of the original data from the request and the paginated data. To remedy …
> fix(types): improve type extraction for namespaced responses and correct async iterator types

- src/iterator.ts
- test/paginate.test.ts
Backport of https://github.com/octokit/plugin-paginate-rest.js/releases/tag/v11.4.1
> fix: ReDos regex vulnerability, reported by @DayShift

- src/types.ts
- test/validate-typescript.ts
Resolves #661
----
* When response data from GitHub is an array, the type would have an extra `OctokitResponse<T, S>` in the data types
* When response data from GitHub is an array, return an empty object in the types
----
> fix(types): correct pagination return type for data which is an array

- .github/workflows/update.yml
Resolves #ISSUE_NUMBER
----
* Would use Node 16 for the update workflow
* Uses the latest LTS release of Node instead of being pinned to a specific version
----
> ci: use `lts/*` version instead of pinning to Node 16

- README.md
- scripts/update-endpoints/typescript.js
- src/generated/paginating-endpoints.ts
- src/iterator.ts
- src/normalize-paginated-list-response.ts
- src/types.ts
- test/issues.test.ts
- test/paginate.test.ts
Resolves #647
----
* `compareCommits` and `compareCommitsWithBasehead` are not correctly paginated.
* `compareCommits` and `compareCommitsWithBasehead` are paginated
No breaking changes (unless someone is using paginate with `compareCommits`, which doesn't work).
----
> feat: Paginate compareCommits and compareCommitsWithBasehead

- src/normalize-paginated-list-response.ts
Resolves N/A
----
Trying to use paginate with the `compareCommitsWithBaseHead` endpoint returns the following error:
```
response.data.total_count = totalCount;
^
TypeError: Cannot create property 'total_count' on string 'https://api.github.com/repos/danger/danger-js/compare/43dde820b424cf11d65e2c42c27b916e162f440a...bdccecb77e0144055fbaea9224f10cf8b1229b68'
at normalizePaginatedListResponse (Directory/node_modules/@octokit/plugin-paginate-rest/dist-bundle/index.js:33:29)
at Object.next (Directory/node_modules/@octokit/plugin-paginate-rest/dist-bundle/index.js:51:38)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async nextData (Directory/test.mjs:16:16)
at async Directory/test.mjs:25:1
```
Pagination for those endpoints and other endpoints continues to …
> fix: handle url in response when using pagination with compareCommits
